name: Selenium Grid Test

on:
  push:
    branches: [ "master"]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:4.1.0
        ports:
          - 4444:4444
    strategy:
      matrix:
        os: [mac]
        browser: [firefox]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven
      - name: Run Selenium Tests
        run: mvn clean test -DremoteDriverUrl=http://selenium:4444/wd/hub -Dos=${{ matrix.os }} -Dbrowser=${{ matrix.browser }} -DsuiteXmlFile=testNg.xml