name: Selenium Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '18'  # You can change this to the version of Java you're using

      - name: Install dependencies
        run: mvn clean install  # Modify this according to your Maven setup

      - name: Run Selenium Tests
        run: mvn test  # Modify this according to your Maven setup
